package com.poke.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CardSetAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCardSetAllPropertiesEquals(CardSet expected, CardSet actual) {
        assertCardSetAutoGeneratedPropertiesEquals(expected, actual);
        assertCardSetAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCardSetAllUpdatablePropertiesEquals(CardSet expected, CardSet actual) {
        assertCardSetUpdatableFieldsEquals(expected, actual);
        assertCardSetUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCardSetAutoGeneratedPropertiesEquals(CardSet expected, CardSet actual) {
        assertThat(actual)
            .as("Verify CardSet auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCardSetUpdatableFieldsEquals(CardSet expected, CardSet actual) {
        assertThat(actual)
            .as("Verify CardSet relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getReleaseDate()).as("check releaseDate").isEqualTo(expected.getReleaseDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCardSetUpdatableRelationshipsEquals(CardSet expected, CardSet actual) {
        // empty method
    }
}
