package com.poke.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PokeUserAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPokeUserAllPropertiesEquals(PokeUser expected, PokeUser actual) {
        assertPokeUserAutoGeneratedPropertiesEquals(expected, actual);
        assertPokeUserAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPokeUserAllUpdatablePropertiesEquals(PokeUser expected, PokeUser actual) {
        assertPokeUserUpdatableFieldsEquals(expected, actual);
        assertPokeUserUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPokeUserAutoGeneratedPropertiesEquals(PokeUser expected, PokeUser actual) {
        assertThat(actual)
            .as("Verify PokeUser auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPokeUserUpdatableFieldsEquals(PokeUser expected, PokeUser actual) {
        assertThat(actual)
            .as("Verify PokeUser relevant properties")
            .satisfies(a -> assertThat(a.getDisplayName()).as("check displayName").isEqualTo(expected.getDisplayName()))
            .satisfies(a -> assertThat(a.getCountry()).as("check country").isEqualTo(expected.getCountry()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPokeUserUpdatableRelationshipsEquals(PokeUser expected, PokeUser actual) {
        // empty method
    }
}
