name: PR Build (Maven)

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

# Cancela ejecuciones previas del mismo PR para no gastar minutos
concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Set up Maven 3.9.9
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: '3.9.9'

      - name: Maven settings (solo Central)
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<'EOF'
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0">
            <mirrors/>
            <profiles>
              <profile>
                <id>public</id>
                <repositories>
                  <repository>
                    <id>central</id>
                    <url>https://repo.maven.apache.org/maven2</url>
                    <releases><enabled>true</enabled></releases>
                    <snapshots><enabled>false</enabled></snapshots>
                  </repository>
                </repositories>
                <pluginRepositories>
                  <pluginRepository>
                    <id>central</id>
                    <url>https://repo.maven.apache.org/maven2</url>
                  </pluginRepository>
                </pluginRepositories>
              </profile>
            </profiles>
            <activeProfiles><activeProfile>public</activeProfile></activeProfiles>
          </settings>
          EOF

      - name: Build
        run: mvn -B -U -DskipITs -DskipTests package

      - name: Upload JAR artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Set up Maven 3.9.9
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: '3.9.9'

      - name: Maven settings (Central)
        run: |
          mkdir -p ~/.m2
          cp -f $GITHUB_WORKSPACE/.github/mvn-settings.xml ~/.m2/settings.xml 2>/dev/null || true

      # Ejecuta tests usando SOLO el cache restaurado (equivalente a offline)
      - name: Run tests (use cache only)
        run: mvn -B -DskipITs test
